
== Before the event

A successful hackfest starts with preparing ahead of time.
Getting your project organized ahead of time means you can spend the event focusing on guiding your contributors.

=== Policy setup

In general, the smaller your project, the less policy structure you need.
But a non-zero sized project requires a non-zero sized set of policies.
(Note that I'm assuming you already have a license.
If not, you are way too far ahead of yourself.)

You policies don't need to be complicated.
For a small project, a sentence or two may be sufficient in some areas.
The goal is to clearly communicate the project's way of working, both as instruction to newcomers and a reminder to experience contributors.

==== Code of conduct

This is one area where I advocate for having a well-defined policy https://duckalignment.academy/code-conduct-enforcement-planning/[ahead of time].
You don't want to be building your code of conduct — particularly the enforcement mechanism — on the fly.
That leads to inconsistent decisions and a process that at least _seems_ unfair.
Both of these can be very harmful to community cohesion.

The point of a code of conduct is to give a https://duckalignment.academy/define-good-behavior/[shared definition of "good" behavior] in human-to-human interactions.
Most people will want to follow the rules of a community.
It’s how community works.
But you can’t rely on everyone having the same unspoken expectations.
Think of it this way:
having rules and policies for behavior in your community is like documenting the community’s API.

In general, I suggest copying an established code of conduct for your community.
The https://www.contributor-covenant.org/[Contributor Covenant] is a flexible, widely-adopted code of conduct.
If you do decide to write your own, include:

* what behaviors you want to encourage and prohibit
* where the policy applies
* how reports are submitted
* who enforces the code of conduct
* what consequences exist for violations

Remember that the point of enforcement is not to be punitive, but to encourage pro-community behavior.
Also bear in mind that for larger communities, enforcement can be a significant emotional burden on those tasked with it.

Ultimately, you can set whatever code of conduct you want for your project.
Enforce it consistently, and you'll get the kind of behavior the code defines as good.

==== Contribution policy

Your project's contribution policy defines the process for submitting a quality contribution and your project's definition of _quality_.
Calling it a "policy" is, perhaps, too strong of a term for most projects.
It tends to be more of a "best practices" document for all but the largest projects where strict policy enforcement becomes necessary.

Although there's no agreed upon standard for a contribution policy, a search of your favorite git forge for "CONTRIBUTING.md" will turn up roughtly eleventy billion examples that you can use as inspiration.
Some things to consider for your contribution policy:

* **Scope.**
Your project won't do everything.
Where are the boundaries for the kinds of contributions you'll accept?
Do you care about typo fixes that don't affect the meaning of docs or websites?
Will you accept new features that aren't already on your roadmap?
What hardware and operating systems do you care to support?
The most technically-brilliant contribution is of no use if it's not something you're willing to accept.
This is an important line to draw because otherwise you will end up stuck supporting something that you have no ability or desire to maintain.
* **Issue creation requirements.**
Does your project require https://duckalignment.academy/adding-pre-report-bug-discussion/[discussion before creating an issue] for a bug report or feature?
Must bug reports be accompanied by a reproducer?
Do bug reports have to be tested against the latest release or the latest commit?
* **Pull request creation requirements.**
Does a pull request need to have an associated issue first?
Does the issue need to be assigned first?
* **Code style requirements.**
What sort of formatting and syntax requirements do you have?
Tabs or spaces?
Fixed-width prose, sentence-per-line, or https://sembr.org/[semantic line breaks]?
* **Testing requirements.**
Do new features have to have tests?
What about changes to un-tested parts of the code base: does a fix there require the addition of a test?
How comprehensive must tests be?
* **Legal-adjacent requirements.**
Does your project require all commits to carry a https://developercertificate.org/[developer certificate of origin] (DCO) signoff?
If not, you'll want to explicitly indicate that contributions are accepted under the project's license ("inbound equals outbound").
* **Branching process.**
What branch should a contribution target?
In other words, is everything against `main` or do you keep release or feature branches separate long-term?
If you maintain multiple branches, how does a would-be contributor know which one to target?
* **Review process.**
Who reviews contributions?
What do they check for?
What automated tests (if any) must pass before a contribution can be accepted?
What should the submitter do if they don't get a response (and how long should they wait)?

If it's not in a separate `GOVERNANCE.md` document, your contribution policy may also include a list of roles in the project, their responsibilities and privileges, and how people move up that ladder.
This isn't strictly necessary for new hackfest contributors, but it will be come relevant if some of them stick around for the longer term.

==== AI Policy

However you feel about AI, it's being used a lot these days.
If you have a strong opinion, you'll need a policy.
If you haven't given it much thought yet, now's the time.
Even if you haven't had to deal with AI contributions yet, it's almost certain that you will once you participate in a hackfest.
I maintain a https://duckalignment.academy/resources/ai-policy-resources/[list of AI policies] used by various projects that you can use as a starting point for creating your own.

Your policy can fall anywhere on a spectrum from "complete and total ban" to "I do not care".
I find Daniel Miessler's https://danielmiessler.com/blog/ai-influence-level-ail[AI Influence Level] (AIL) system to be a good conceptual framework.
You can pick the highest number you're willing to accept and use that as a starting point for creating your policy.

A "no AI usage at all" policy doesn't have to be very complicated.
if you allow some amount of AI usage, then you'll want to consider if and how you want it disclosed.
Some projects, like the Linux kernel, have a https://docs.kernel.org/process/coding-assistants.html#attribution[defined attribution style] to follow.
On the other hand, Kubernetes https://www.kubernetes.dev/docs/guide/pull-requests/#ai-guidance[expressly forbids] commit message trailers to prevent unscrupulous vendors from using that for marketing.

In addition to use and disclosure rules, there's one more thing you'll want to consider:
can AI be used on "good first issues"…issues?
More specifically, perhaps, can autonomous AI agents contribute to those issues?
This may be something you want to special-case for a hackfest, depending on the reasons for participation that you came up with.
If you're participating in the event with a primary purpose of helping new contributors get experience in open source software, then letting AI agents grab the "good first issue" issues defeats the purpose.
Personally, I think anything that you took the time to mark as a good first issue should be left for the newcomer humans to work on.

Once you've developed an AI policy, you should put the bits that you want AI tools to know about in an https://agents.md/[AGENTS.md file].
This has become a quasi-standard way of providing AI-specific instructions.
Of course, there's no guarantee that the model will follow it.

==== Security policy

Speaking of things that are necessary these days, you'll also want to have a security policy.
This primarily covers how you want people to report security issues and how you'll handle those reports.
To be clear: you are under no obligation to handle security reports in any way except the way you want to.

A common approach is to have a private mechanism for reports — often an email address or a privuate issue (if your platform supports it).
This keeps the details under wraps so that you have time to fix it.
Your policy should indicate how quickly you'll respond to security issues.
This doesn't necessarily mean how quickly you'll _fix_ the issue, just how long the reporter should wait for acknowledgement.

Often, researchers will set a date on which they'll disclose the vulnerability to coincide with the release of your patch, a process known as "coordinated disclosure."
Of course, some projects also choose to treat vulnerability reports the same as any other bug because the overhead of coordinated disclosure is too great a burden for them.

Your policy should also make clear what version(s) you'll accept security reports for.
Once you have all of this together, you should put it in a `SECURITY.md` file in the root of your repo.

=== Codebase setup

Of course, getting your code ready is an important step in preparing for an influx of newcomers.

==== Audit your docs

A good starting point is to walk through your docs and make sure they're still accurate.
Do the instructions for building the project and running your test suite still work?
Are all of the requirements listed?
If not, your new contributors are going to have a rough time.

The best way to test your documentation is to have someone who is unfamiliar with your project attempt to clone, build, and test your code.
Any place they struggle is a bug in your docs.
If you can't find a friend to test your docs, you can follow your instructions on a fresh virtual machine.
The odds are decent that you'll find some required tool or library that's not included in your docs.

When updating your docs to address any gaps you found, bear in mind that your reader will know a lot less about your project than you do.
It's better to over-explain than under-explain.
This doesn't mean you have to write paragraphs explaining how to use the test suite— a simple link to official docs will do — but it's better to give example commands than to just say something like "run the tests".

==== Plan your roadmap

Do you know what's next for your project?
Your new contributors won't unless you write it down.
Creating a project roadmap helps people know what you would like them to work on.
Of course, they may come with their own ideas, too.
But having a documented "we want this" makes it clear that the work is in scope for the project.

The roadmap doesn't have to be fancy.
You can just open issues for the things you'd like to see done.
This way you can record any details about design, acceptance criteria, and so on.
Don't limit your self to features, either.
Open issues for known bugs and meta work (like documentation, testing, etc), too.

If your motivation for participating in the event includes getting work done on features or bugfixes and you haven't set a roadmap of some kind, you're setting yourself up for disappointment.

==== Set code style requirements

=== Repo meta setup

==== Tags

==== CI workflows

==== Security settings

==== Issue templates

=== Community setup

==== How will people communicate?

==== Can anyone help you?

=== Gifts?
