
== Before the event

A successful hackfest starts with preparing ahead of time.
Getting your project organized ahead of time means you can spend the event focusing on guiding your contributors.

=== Policy setup

In general, the smaller your project, the less policy structure you need.
But a non-zero sized project requires a non-zero sized set of policies.
(Note that I'm assuming you already have a license.
If not, you are way too far ahead of yourself.)

You policies don't need to be complicated.
For a small project, a sentence or two may be sufficient in some areas.
The goal is to clearly communicate the project's way of working, both as instruction to newcomers and a reminder to experience contributors.

==== Code of conduct

This is one area where I advocate for having a well-defined policy https://duckalignment.academy/code-conduct-enforcement-planning/[ahead of time].
You don't want to be building your code of conduct — particularly the enforcement mechanism — on the fly.
That leads to inconsistent decisions and a process that at least _seems_ unfair.
Both of these can be very harmful to community cohesion.

The point of a code of conduct is to give a https://duckalignment.academy/define-good-behavior/[shared definition of "good" behavior] in human-to-human interactions.
Most people will want to follow the rules of a community.
It’s how community works.
But you can’t rely on everyone having the same unspoken expectations.
Think of it this way:
having rules and policies for behavior in your community is like documenting the community’s API.

In general, I suggest copying an established code of conduct for your community.
The https://www.contributor-covenant.org/[Contributor Covenant] is a flexible, widely-adopted code of conduct.
If you do decide to write your own, include:

* what behaviors you want to encourage and prohibit
* where the policy applies
* how reports are submitted
* who enforces the code of conduct
* what consequences exist for violations

Remember that the point of enforcement is not to be punitive, but to encourage pro-community behavior.
Also bear in mind that for larger communities, enforcement can be a significant emotional burden on those tasked with it.

Ultimately, you can set whatever code of conduct you want for your project.
Enforce it consistently, and you'll get the kind of behavior the code defines as good.

==== Contribution policy

Your project's contribution policy defines the process for submitting a quality contribution and your project's definition of _quality_.
Calling it a "policy" is, perhaps, too strong of a term for most projects.
It tends to be more of a "best practices" document for all but the largest projects where strict policy enforcement becomes necessary.

Although there's no agreed upon standard for a contribution policy, a search of your favorite git forge for "CONTRIBUTING.md" will turn up roughtly eleventy billion examples that you can use as inspiration.
Some things to consider for your contribution policy:

* **Scope.**
Your project won't do everything.
Where are the boundaries for the kinds of contributions you'll accept?
Do you care about typo fixes that don't affect the meaning of docs or websites?
Will you accept new features that aren't already on your roadmap?
What hardware and operating systems do you care to support?
The most technically-brilliant contribution is of no use if it's not something you're willing to accept.
This is an important line to draw because otherwise you will end up stuck supporting something that you have no ability or desire to maintain.
* **Issue creation requirements.**
Does your project require https://duckalignment.academy/adding-pre-report-bug-discussion/[discussion before creating an issue] for a bug report or feature?
Must bug reports be accompanied by a reproducer?
Do bug reports have to be tested against the latest release or the latest commit?
* **Pull request creation requirements.**
Does a pull request need to have an associated issue first?
Does the issue need to be assigned first?
* **Code style requirements.**
What sort of formatting and syntax requirements do you have?
Tabs or spaces?
Fixed-width prose, sentence-per-line, or https://sembr.org/[semantic line breaks]?
* **Testing requirements.**
Do new features have to have tests?
What about changes to un-tested parts of the code base: does a fix there require the addition of a test?
How comprehensive must tests be?
* **Legal-adjacent requirements.**
Does your project require all commits to carry a https://developercertificate.org/[developer certificate of origin] (DCO) signoff?
If not, you'll want to explicitly indicate that contributions are accepted under the project's license ("inbound equals outbound").
* **Branching process.**
What branch should a contribution target?
In other words, is everything against `main` or do you keep release or feature branches separate long-term?
If you maintain multiple branches, how does a would-be contributor know which one to target?
* **Review process.**
Who reviews contributions?
What do they check for?
What automated tests (if any) must pass before a contribution can be accepted?
What should the submitter do if they don't get a response (and how long should they wait)?

If it's not in a separate `GOVERNANCE.md` document, your contribution policy may also include a list of roles in the project, their responsibilities and privileges, and how people move up that ladder.
This isn't strictly necessary for new hackfest contributors, but it will be come relevant if some of them stick around for the longer term.

==== AI Policy

==== Security policy


=== Codebase setup

==== Plan your roadmap

==== Open issues

==== Improve your docs

==== Set code style requirements

=== Repo setup

==== Tags

==== CI workflows

==== Security settings

==== Issue templates

=== Community setup

==== How will people communicate?

==== Can anyone help you?

=== Gifts?
