name: Build book

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
        with:
          persist-credentials: false
      - name: Install toolchain
        run: sudo apt-get install -y asciidoctor ruby-asciidoctor-pdf pandoc
      - name: Build book
        run: make all
      - name: Upload output
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # tag=v4.4.3
        with:
          name: hackfest-guide-${{ github.sha }}
          path: output/

  release:
    runs-on: ubuntu-latest
    needs: build-book
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: 
      contents: write
    steps:
      - name: Download files
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # tag=v8.0.1
      - name: Create Release via GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for the gh CLI to authenticate
          RELEASE_TAG: ${{ gitub.ref_name}}
        run: |
          gh release create "${RELEASE_TAG}" \
            hackfest-guide-${{ github.sha }}/hackfest-guide.pdf \
            hackfest-guide-${{ github.sha }}/hackfest-guide.epub \
            --title "Version ${RELEASE_TAG}" \
            --generate-notes
