name: Check spelling

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          persist-credentials: false
      - name: Install toolchain
        run: sudo apt-get install -y hunspell
      - name: Check spelling
        run: make spellcheck
